data_ingestion:
  data_set_source: "online"
  data_set_name: "airline_passengers"
  data_set_store_path: "data/raw_data"
  data_set_path: ""
  data_set_url: 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv'

data_preprocessing:
  store_path: "data/preprocessed_data"
  min_max_scale: False
  standard_scale: False
  train_ratio: 0.7
  test_ratio: 0.2
  val_ratio: 0.1


model_training:
  model_name: "TFT"
  model_save_path: "saved_models"

TFT_model:
  history_length: 5
  prediction_length: 1
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  device: "auto"

ARIMA_model:
  data_name: sunspots
  p: 5
  d: 1
  q: 2

