data_ingestion:
  data_set_source: "local"
  data_set_name: "airline_passengers"
  data_set_store_path: "data/raw_data"
  data_set_path: ""
  data_set_url: ""

data_preprocessing:
  store_path: "data/processed_data"
  min_max_scale: False
  standard_scale: False
  train_test_split_ratio: 0.8


model_training:
  model_name: "TFT"
  model_save_path: "saved_models"

TFT_model:
  history_length: 5
  prediction_length: 1
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  device: "auto"
