data_ingestion:
  data_set_source: "online"
  data_set_name: "airline_passengers"
  data_set_store_path: "data/raw_data"
  data_set_path: ""
  data_set_url: 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv'

data_preprocessing:
  store_path: "data/preprocessed_data"
  min_max_scale: False
  standard_scale: False
  train_ratio: 0.7
  test_ratio: 0.3
  


model_training:
  model_name: "TFT"
  model_save_path: "saved_models"

TFT_model:
  max_encoder_length: 5
  max_prediction_length: 10
  device: "mps"
  batch_size: 16
  epochs: 10
  learning_rate: 0.001
  

ARIMA_model:
  data_name: sunspots
  p: 5
  d: 1
  q: 2

results:
  plots_path: "results/plots"
